apps/events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    path('', views.EventList.as_view(), name='list'),
    path('<int:year>/', views.EventListYear.as_view(), name='list_year'),
    path('<int:year>/<slug:slug>/', views.EventDetail.as_view(), name='detail'),
]

foxtail/urls.py
# flake8: noqa

"""foxtail URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

import apps.content.sitemaps as content_sitemaps
import apps.core.views as core_views
import apps.events.sitemaps as event_sitemaps
import foxtail_blog.sitemaps as blog_sitemaps

sitemaps = {
    'static': content_sitemaps.StaticSitemap,
    'page': content_sitemaps.PageSitemap,
    'post': blog_sitemaps.PostSitemap,
    'event': event_sitemaps.EventSitemap,
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', core_views.robots, name='robots'),
    path('.well-known/openid-configuration/', core_views.redirect_provider_info),
    path('admin/django-rq/', include('django_rq.urls')),
    path('admin/', admin.site.urls),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
    path('accounts/', include('apps.accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('directory/', include('apps.directory.urls')),
    path('events/', include('apps.events.urls')),
    path('contact/', include('foxtail_contact.urls')),
    path('blog/', include('foxtail_blog.urls')),
    path('', include('apps.content.urls'))
]

handler500 = 'apps.core.views.handler_500'


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

    if not settings.AZURE_MEDIA:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/events/models.py
from datetime import datetime, timedelta

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.html import strip_tags
from django.utils.text import Truncator
from django.utils.timezone import now

from markdownfield.models import MarkdownField, RenderedMarkdownField
from markdownfield.validators import VALIDATOR_CLASSY
from pytz import utc
from slugger import AutoSlugField
from taggit.managers import TaggableManager
from versatileimagefield.fields import PPOIField, VersatileImageField


class Event(models.Model):
    title = models.CharField(max_length=100, help_text="100 characters or fewer.")
    slug = AutoSlugField(populate_from='title', unique_for_year='start')
    tags = TaggableManager(blank=True)

    description = MarkdownField(rendered_field='description_rendered', validator=VALIDATOR_CLASSY)
    description_rendered = RenderedMarkdownField()
    url = models.URLField(blank=True)

    location = models.CharField(max_length=200)
    address = models.TextField(blank=True)

    start = models.DateField()
    start_time = models.TimeField(null=True, blank=True, help_text="Time is optional.")
    end = models.DateField(null=True, blank=True, help_text="End date and time are optional.")
    end_time = models.TimeField(null=True, blank=True, help_text="End date and time are optional.")

    image = VersatileImageField(upload_to='events', blank=True, null=True, ppoi_field='image_ppoi')
    image_ppoi = PPOIField()

    created = models.DateTimeField(auto_now_add=True, verbose_name="date created")
    modified = models.DateTimeField(auto_now=True, verbose_name="date modified")

    class Meta:
        ordering = ["start"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('events:detail', kwargs={'year': self.start.year, 'slug': self.slug})

    @property
    def is_ended(self):
        if self.end:
            end = datetime.combine(self.end, self.end_time) if self.end_time else\
                datetime.combine(self.end, datetime.min.time(), tzinfo=utc)
        else:
            end = datetime.combine(self.start, self.end_time) if self.end_time else (self.start + timedelta(days=1))

        return end < now()

    @cached_property
    def structured_data(self):
        url = settings.SITE_URL + self.get_absolute_url()
        data = {
            '@type': 'Event',
            'name': self.title,
            'description': self.description or Truncator(strip_tags(self.description_rendered)).chars(200),
            'startDate': self.start.strftime('%Y-%m-%d'),
            'url': url,
            'mainEntityOfPage': {
                '@type': 'WebPage',
                '@id': url
            },
        }

        if self.end:
            data['endDate'] = self.end.strftime('%Y-%m-%d')

        if self.location:
            data['location'] = {
                '@type': 'Place',
                'name': self.location,
                'address': self.address or self.location,
            }

        if self.image:
            data['image'] = {
                '@type': 'ImageObject',
                'url': self.image.url,
                'height': self.image.height,
                'width': self.image.width
            }

        return data

apps/events/views.py
from datetime import datetime

from django.http import Http404
from django.views.generic import DetailView, ListView
from django.views.generic.dates import YearMixin

from .models import Event


class EventList(ListView):
    queryset = Event.objects.all().prefetch_related('tags')
    ordering = '-start'
    template_name = 'event_list.html'
    context_object_name = 'event_list'


class EventListYear(YearMixin, ListView):
    ordering = 'start'
    template_name = 'event_list.html'
    context_object_name = 'event_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['year'] = str(self.get_year())
        return context

    def get_queryset(self):
        try:
            date = datetime.strptime(str(self.get_year()), self.get_year_format())
        except ValueError:
            raise Http404()

        return Event.objects.filter(
            start__year=date.year
        ).prefetch_related('tags')


class EventDetail(YearMixin, DetailView):
    model = Event
    template_name = 'event_detail.html'

    def get_queryset(self):
        try:
            date = datetime.strptime(str(self.get_year()), self.get_year_format())
        except ValueError:
            raise Http404()

        return Event.objects.filter(
            start__year=date.year,
            slug=self.kwargs['slug']
        )


__all__ = ['EventList', 'EventDetail']

apps/events/templates/event_detail.html
{% extends "base.html" %}
{% load icon cache jsonld opengraph meta %}

{% block extra_head %}
    <link rel="canonical" href="{{ SITE_URL }}{{ event.get_absolute_url }}"/>
    <meta name="twitter:card" content="summary_large_image"/>
    {% json_ld_for event %}
    {% og_for event %}
    {% meta_for event %}
    <script type="application/ld+json">
        {
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            "itemListElement": [
                {
                    "@type": "ListItem",
                    "position": 1,
                    "name": "Events",
                    "item": "{{ SITE_URL }}{% url 'events:list' %}"
                },
                {
                    "@type": "ListItem",
                    "position": 2,
                    "name": "{{ event.start.year }}",
                    "item": "{{ SITE_URL }}{% url 'events:list_year' year=event.start.year %}"
                },
                {
                    "@type": "ListItem",
                    "position": 3,
                    "name": "{{ event.title }}",
                    "item": "{{ SITE_URL }}{{ event.get_absolute_url }}"
                }
            ]
        }
    </script>

{% endblock %}

{% block title %}{{ event.title }}{% endblock %}

{% block content %}
    <div class="card text-white bg-dark">
        {% if event.image %}
            <img class="card-img-top" src="{{ event.image.crop.1150x300 }}" alt="">
        {% endif %}

        <div class="card-body">
            <h4 class="card-title mb-2">{{ event.title }}</h4>
            <h5 class="card-subtitle mb-2">{{ event.location }}</h5>
            <div class="rendered-markdown">
                {{ event.description_rendered | safe }}
            </div>
            <h6 class="mb-0">Starts</h6>
            <p>{{ event.start | date:"F jS, Y" }}{{ event.start_time | time:", \a\t P" }}</p>

            {# template clusterfuck that handles any combination of inputs #}
            {% if event.end or event.end_time %}
                <h6 class="mb-0">Ends</h6>
                {% spaceless %}
                    {% if event.end %}
                        {% if event.end == event.start %}
                            <p>Same day, at {{ event.end_time | time:"P" }}</p>
                        {% else %}
                            <p>{{ event.end | date:"F jS, Y" }}{{ event.end_time | time:", \a\t P" }}</p>
                        {% endif %}
                    {% else %}
                        <p>Same day, at {{ event.end_time | time:"P" }}</p>
                    {% endif %}
                {% endspaceless %}
            {% endif %}

            {% if event.url %}
                <a class="btn btn-primary" href="{{ event.url }}" rel="noopener noreferrer" target="_blank">
                    View event website
                </a>
            {% endif %}
        </div>
        {% if event.tags %}
            <div class="card-footer">
                {% for tag in event.tags.all %}
                    {{ tag.name | title }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock content %}

apps/events/templates/event_list.html
{% extends "base.html" %}
{% load icon %}

{% block title %}Upcoming Furry Events{% endblock %}

{% block extra_head %}
    {% if year %}
        <script type="application/ld+json">
            {
                "@context": "https://schema.org",
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": 1,
                        "name": "Events",
                        "item": "{{ SITE_URL }}{% url 'events:list' %}"
                    },
                    {
                        "@type": "ListItem",
                        "position": 2,
                        "name": "{{ year }}",
                        "item": "{{ SITE_URL }}{% url 'events:list_year' year=year %}"
                    }
                ]
            }
        </script>
    {% else %}
        <script type="application/ld+json">
            {
                "@context": "https://schema.org",
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": 1,
                        "name": "Events",
                        "item": "{{ SITE_URL }}{% url 'events:list' %}"
                    }
                ]
            }
        </script>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row narrow-gutters" data-colcade="columns: .grid-col, items: .card">
        <div class="grid-col col-md-6 col-lg-4"></div>
        <div class="grid-col d-none d-md-block col-md-6 col-lg-4"></div>
        <div class="grid-col d-none d-lg-block col-md-6 col-lg-4"></div>
        {% for event in event_list %}
            <div class="col-md-6 col-lg-4">
                <div class="card text-white bg-dark mb-3">
                    {% if event.image %}
                        <a href="{{ event.get_absolute_url }}">
                            <img class="card-img-top"
                                 src="{{ event.image.crop.350x175 }}"
                                 srcset="{{ event.image.crop.350x175 }} 1x, {{ event.image.crop.700x350 }} 2x"
                                 alt="">
                        </a>
                    {% endif %}

                    <div class="card-body">
                        <h5 class="card-title mb-2">{{ event.title }}</h5>
                        <h6 class="card-subtitle mb-2">{{ event.location }}</h6>
                        <p class="card-text">{{ event.description_rendered | safe | striptags | truncatechars:120 }}</p>
                        <p class="card-text"><strong>{{ event.start | date:"F jS, Y" }}</strong></p>
                        <a href="{{ event.get_absolute_url }}" class="btn btn-primary">View Event</a>
                    </div>
                    {% if event.tags %}
                        <div class="card-footer">
                            {% for tag in event.tags.all %}
                                <small>{{ tag.name | title }}{% if not forloop.last %}, {% endif %}</small>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        {% empty %}
            <p>No events were found.</p>
        {% endfor %}
    </div>
{% endblock content %}