apps/content/urls.py
from django.urls import path

from . import views

app_name = 'content'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<slug:slug>/', views.PageView.as_view(), name='page'),
]

apps/directory/urls.py
from django.conf import settings
from django.urls import path

from . import views

app_name = 'directory'
urlpatterns = []

if settings.DIRECTORY_ENABLED:
    urlpatterns += [
        path('', views.ProfileListView.as_view(), name='index'),

        # creation
        path('create/', views.ProfileCreateView.as_view(), name='profile_create'),

        # modification
        path('<slug:slug>/edit/', views.ProfileEditView.as_view(), name='profile_edit'),
        path('<slug:slug>/<int:pk>/edit/', views.CharacterEditView.as_view(), name='character_edit'),

        # placed at the end to not override earlier views
        path('<slug:slug>/', views.ProfileView.as_view(), name='profile'),
        path('<slug:slug>/<int:pk>/', views.CharacterView.as_view(), name='character'),
    ]

apps/events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    path('', views.EventList.as_view(), name='list'),
    path('<int:year>/', views.EventListYear.as_view(), name='list_year'),
    path('<int:year>/<slug:slug>/', views.EventDetail.as_view(), name='detail'),
]

foxtail/urls.py
# flake8: noqa

"""foxtail URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

import apps.content.sitemaps as content_sitemaps
import apps.core.views as core_views
import apps.events.sitemaps as event_sitemaps
import foxtail_blog.sitemaps as blog_sitemaps

sitemaps = {
    'static': content_sitemaps.StaticSitemap,
    'page': content_sitemaps.PageSitemap,
    'post': blog_sitemaps.PostSitemap,
    'event': event_sitemaps.EventSitemap,
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', core_views.robots, name='robots'),
    path('.well-known/openid-configuration/', core_views.redirect_provider_info),
    path('admin/django-rq/', include('django_rq.urls')),
    path('admin/', admin.site.urls),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
    path('accounts/', include('apps.accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('directory/', include('apps.directory.urls')),
    path('events/', include('apps.events.urls')),
    path('contact/', include('foxtail_contact.urls')),
    path('blog/', include('foxtail_blog.urls')),
    path('', include('apps.content.urls'))
]

handler500 = 'apps.core.views.handler_500'


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

    if not settings.AZURE_MEDIA:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/footer.html
{% load tz %}
{% get_current_timezone as TIME_ZONE %}
<footer id="footer">
    <div class="container">
        <p>{{ request.site.name }} —
            <a href="https://github.com/dmptrluke/foxtail" target="_blank" rel="noopener noreferrer">source</a>,
            <a href="{% url 'content:page' slug='privacy' %}">privacy</a>,
            <a href="{% url 'contact:contact'%}">contact</a>,

            <a role="button" data-bs-toggle="popover" data-bs-placement="top"
            data-bs-content="'{{ DEBUG_DATA | escape }}'">?</a>
        </p>
    </div>
</footer>

templates/components/header.html
{% load icon %}
<nav id="navigation" class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'content:index' %}">{% icon 'paw' %}{{ request.site.name }}</a>
      {% include "components/nav.html" %}
  </div>
</nav>

templates/components/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible fade show mb-4" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endfor %}

templates/components/nav.html
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse" id="navbar">
    {# main navigation #}
    <div class="navbar-nav me-auto mb-2 mb-lg-0">
        <a class="nav-item nav-link{% if request.resolver_match.app_name == "blog" %} active{% endif %}"
           href="{% url 'blog:list' %}">News</a>
        <a class="nav-item nav-link{% if request.resolver_match.app_name == "events" %} active{% endif %}"
           href="{% url 'events:list' %}">Events</a>
        {% if DIRECTORY_ENABLED %}
            <a class="nav-item nav-link{% if request.resolver_match.app_name == "directory" %} active{% endif %}"
           href="{% url 'directory:index' %}">Directory</a>
        {% endif %}
    </div>
    {# user menu #}
    <div class="navbar-nav">
        {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle{% if "account_" in request.resolver_match.url_name %} active{% endif %}"
                   href="#" id="account-dropdown" role="button" data-bs-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="account-dropdown">
                    <a class="dropdown-item" href="{% url 'account_profile' %}">Manage Account</a>
                    {% if user.is_staff %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Admin Panel</a>
                    {% endif %}
                    <div class="dropdown-divider"></div>
                    <form method="post" action="{% url 'account_logout' %}?next={{ request.path }}">
                        {% csrf_token %}
                        <input type="submit" class="dropdown-item" value="Sign Out">
                    </form>
                </div>
            </li>
        {% else %}
            <a class="nav-item nav-link" href="{% url 'account_login' %}">Sign In</a>
        {% endif %}
    </div>
</div>

templates/components/pagination.html
{% load url_transform %}

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="?{% url_transform page=page_obj.previous_page_number %}" class="page-link">
                    Previous
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">
                    Previous
                </span>
            </li>
        {% endif %}

        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active"><a class="page-link">{{ i }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?{% url_transform page=i %}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a href="?{% url_transform page=page_obj.next_page_number %}" class="page-link">
                    Next
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">
                    Next
                </span>
            </li>
        {% endif %}
    </ul>
</nav>

templates/components/provider_list.html
{% load socialaccount icon %}
{% get_providers as socialaccount_providers %}

{% for provider in socialaccount_providers %}
    {% if provider.id == "openid" %}
        {% for brand in provider.get_brands %}
            <div class="btn-group">
                <a title="{{ brand.name }}"
                   class="socialaccount_provider {{ provider.id }} {{ brand.id }} btn btn-outline-primary mb-1"
                   href="{% provider_login_url provider.id openid=brand.openid_url process=process %}"
                >{% icon brand.name %} {{ brand.name }}</a>
            </div>
        {% endfor %}
    {% endif %}
    <div class="btn-group">
        <a title="{{ provider.name }}" class="socialaccount_provider {{ provider.id }} btn btn-outline-primary mb-1"
           href="{% provider_login_url provider.id process=process scope=scope auth_params=auth_params %}">
            {% icon provider.name|lower %} {{ provider.name }}
        </a>
    </div>
{% endfor %}

templates/components/publish_status.html
{% load model_name %}
{% if not object.available_to_public %}
    {% if object.publish_status == 2 %}
        <div class="alert alert-warning mb-4" role="alert">
            This {{ object | get_model_name | lower }} is not yet available to the public. It will be published @
            {{ object.live_as_of |date:"SHORT_DATETIME_FORMAT" }}
        </div>
    {% elif object.publish_status == 0 %}
        <div class="alert alert-danger mb-4" role="alert">
            This {{ object | get_model_name | lower }} is not available to the public.
        </div>
    {% endif %}
{% endif %}